export const chemicals = [
    // Chemical Compounds
    { id: 1, name: 'Sulfuric Acid', formula: 'H2SO4', color: '#f0dc82' },
    { id: 2, name: 'Hydrochloric Acid', formula: 'HCl', color: '#e6e6e6' },
    { id: 3, name: 'Nitric Acid', formula: 'HNO3', color: '#ffd700' },
    { id: 4, name: 'Sodium Hydroxide', formula: 'NaOH', color: '#ffffff' },
    { id: 5, name: 'Potassium Hydroxide', formula: 'KOH', color: '#ffffff' },
    { id: 6, name: 'Calcium Carbonate', formula: 'CaCO3', color: '#f5f5f5' },
    { id: 7, name: 'Sodium Chloride', formula: 'NaCl', color: '#ffffff' },
    { id: 8, name: 'Copper Sulfate', formula: 'CuSO4', color: '#4169e1' },
    { id: 9, name: 'Iron(III) Chloride', formula: 'FeCl3', color: '#8b4513' },
    { id: 10, name: 'Silver Nitrate', formula: 'AgNO3', color: '#c0c0c0' },
    { id: 11, name: 'Sodium Carbonate', formula: 'Na2CO3', color: '#ffffff' },
    { id: 12, name: 'Potassium Chloride', formula: 'KCl', color: '#ffffff' },
    { id: 13, name: 'Calcium Hydroxide', formula: 'Ca(OH)2', color: '#ffffff' },
    { id: 14, name: 'Magnesium Sulfate', formula: 'MgSO4', color: '#b0c4de' },
    { id: 15, name: 'Barium Chloride', formula: 'BaCl2', color: '#ff6347' },
    { id: 16, name: 'Copper(II) Chloride', formula: 'CuCl2', color: '#00bfff' },
    { id: 17, name: 'Lead(II) Nitrate', formula: 'Pb(NO3)2', color: '#ffff00' },
    { id: 18, name: 'Zinc Sulfate', formula: 'ZnSO4', color: '#f0e68c' },
    { id: 19, name: 'Ammonium Nitrate', formula: 'NH4NO3', color: '#ffb6c1' },
    { id: 20, name: 'Iron(II) Sulfate', formula: 'FeSO4', color: '#d3d3d3' },
    { id: 21, name: 'Magnesium Chloride', formula: 'MgCl2', color: '#f8f8ff' },
    { id: 22, name: 'Calcium Chloride', formula: 'CaCl2', color: '#f0f8ff' },

    // Elements from the Periodic Table
    { id: 23, name: 'Hydrogen', formula: 'H2', color: '#ff4500' },
    { id: 24, name: 'Helium', formula: 'He', color: '#ff6347' },
    { id: 25, name: 'Lithium', formula: 'Li', color: '#f08080' },
    { id: 26, name: 'Beryllium', formula: 'Be', color: '#b0e0e6' },
    { id: 27, name: 'Boron', formula: 'B', color: '#00fa9a' },
    { id: 28, name: 'Carbon', formula: 'C', color: '#a9a9a9' },
    { id: 29, name: 'Nitrogen', formula: 'N2', color: '#4682b4' },
    { id: 30, name: 'Oxygen', formula: 'O2', color: '#ff0000' },
    { id: 31, name: 'Fluorine', formula: 'F2', color: '#32cd32' },
    { id: 32, name: 'Neon', formula: 'Ne', color: '#ffff00' },
    { id: 33, name: 'Sodium', formula: 'Na', color: '#d2691e' },
    { id: 34, name: 'Magnesium', formula: 'Mg', color: '#a52a2a' },
    { id: 35, name: 'Aluminum', formula: 'Al', color: '#778899' },
    { id: 36, name: 'Silicon', formula: 'Si', color: '#808080' },
    { id: 37, name: 'Phosphorus', formula: 'P', color: '#dda0dd' },
    { id: 38, name: 'Sulfur', formula: 'S', color: '#ffff00' },
    { id: 39, name: 'Chlorine', formula: 'Cl2', color: '#32cd32' },
    { id: 40, name: 'Argon', formula: 'Ar', color: '#ff6347' },
    { id: 41, name: 'Potassium', formula: 'K', color: '#b22222' },
    { id: 42, name: 'Calcium', formula: 'Ca', color: '#ff8c00' },
    { id: 43, name: 'Scandium', formula: 'Sc', color: '#1e90ff' },
    { id: 44, name: 'Titanium', formula: 'Ti', color: '#d3d3d3' },
    { id: 45, name: 'Vanadium', formula: 'V', color: '#bdb76b' },
    { id: 46, name: 'Chromium', formula: 'Cr', color: '#8b0000' },
    { id: 47, name: 'Manganese', formula: 'Mn', color: '#a52a2a' },
    { id: 48, name: 'Iron', formula: 'Fe', color: '#b22222' },
    { id: 49, name: 'Cobalt', formula: 'Co', color: '#7f7f7f' },
    { id: 50, name: 'Nickel', formula: 'Ni', color: '#32cd32' },
    { id: 51, name: 'Copper', formula: 'Cu', color: '#ff8c00' },
    { id: 52, name: 'Zinc', formula: 'Zn', color: '#c0c0c0' },
    { id: 53, name: 'Gallium', formula: 'Ga', color: '#90ee90' },
    { id: 54, name: 'Germanium', formula: 'Ge', color: '#d3d3d3' },
    { id: 55, name: 'Arsenic', formula: 'As', color: '#a9a9a9' },
    { id: 56, name: 'Selenium', formula: 'Se', color: '#f0e68c' },
    { id: 57, name: 'Bromine', formula: 'Br2', color: '#ff4500' },
    { id: 58, name: 'Krypton', formula: 'Kr', color: '#ff6347' },
    { id: 59, name: 'Rubidium', formula: 'Rb', color: '#b22222' },
    { id: 60, name: 'Strontium', formula: 'Sr', color: '#ff8c00' },
    { id: 61, name: 'Yttrium', formula: 'Y', color: '#ff00ff' },
    { id: 62, name: 'Zirconium', formula: 'Zr', color: '#d3d3d3' },
    { id: 63, name: 'Niobium', formula: 'Nb', color: '#f0e68c' },
    { id: 64, name: 'Molybdenum', formula: 'Mo', color: '#808080' },
    { id: 65, name: 'Technetium', formula: 'Tc', color: '#b0e0e6' },
    { id: 66, name: 'Ruthenium', formula: 'Ru', color: '#ff6347' },
    { id: 67, name: 'Rhodium', formula: 'Rh', color: '#dda0dd' },
    { id: 68, name: 'Palladium', formula: 'Pd', color: '#7f7f7f' },
    { id: 69, name: 'Silver', formula: 'Ag', color: '#c0c0c0' },
    { id: 70, name: 'Cadmium', formula: 'Cd', color: '#ffebcd' },
    { id: 71, name: 'Indium', formula: 'In', color: '#7f7f7f' },
    { id: 72, name: 'Tin', formula: 'Sn', color: '#d3d3d3' },
    { id: 73, name: 'Antimony', formula: 'Sb', color: '#b0c4de' },
    { id: 74, name: 'Tellurium', formula: 'Te', color: '#8b4513' },
    { id: 75, name: 'Iodine', formula: 'I2', color: '#800080' },
    { id: 76, name: 'Xenon', formula: 'Xe', color: '#32cd32' },
    { id: 77, name: 'Cesium', formula: 'Cs', color: '#ff0000' },
    { id: 78, name: 'Barium', formula: 'Ba', color: '#ff8c00' }
];
